name: first_login
description: "A new Flutter project."



version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  pdf: ^3.10.3
  printing: ^5.12.0
  path_provider: ^2.1.1
#  open_file: ^3.3.2
  permission_handler: ^11.3.0
  flutter_to_pdf: ^0.4.1
  share_plus: ^7.2.2
  file_picker: ^8.0.6
  media_store_plus: ^0.1.3
  open_filex: ^4.3.4
#  syncfusion_flutter_pdfviewer: ^23.1.36


  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  http: ^1.4.0

  flutter_lints: ^5.0.0




flutter:

  assets:
    - assets/images/


  uses-material-design: true

fonts:
  - family: Montserrat
    fonts:
      - assets: fonts/Open_Sans/static/OpenSans-ExtraBoldItalic.ttf
      - assets: fonts/Poppins/Poppins-Bold.ttf
      - assets: fonts/Montserrat/static/Montserrat-Bold.ttf
      - assets: fonts/Roboto/static/Roboto-Bold.ttf


